package com.chukimmuoi.model

/**
 * @author: My Project
 * @Skype: chukimmuoi
 * @Mobile : +84 167 367 2505
 * @Email: chukimmuoi@gmail.com
 * @Website: https://github.com/chukimmuoi
 * @Project: StockVN
 * Created by chukimmuoi on 05/12/2022.
 */
data class StockPrice(
    val adAverage: Double = 0.0,
    val adChange: Double = 0.0,
    val adClose: Double = 0.0,
    val adHigh: Double = 0.0,
    val adLow: Double = 0.0,
    val adOpen: Double = 0.0,
    val average: Double = 0.0,
    val basicPrice: Double = 0.0,
    val ceilingPrice: Double = 0.0,
    val change: Double = 0.0,
    val close: Double = 0.0,
    val code: String = "",
    val date: String = "",
    val floor: String = "",
    val floorPrice: Double = 0.0,
    val high: Double = 0.0,
    val low: Double = 0.0,
    val nmValue: Double = 0.0,
    val nmVolume: Double = 0.0,
    val `open`: Double = 0.0,
    val pctChange: Double = 0.0,
    val ptValue: Double = 0.0,
    val ptVolume: Double = 0.0,
    val time: String = "",
    val type: String = ""
)

val previewStockPrice = listOf(
    StockPrice(
        code = "VNI",
        date = "2022-10-06",
        time = "15:10:01",
        floor = "UPCOM",
        type = "STOCK",
        basicPrice = 12.7,
        ceilingPrice = 14.6,
        floorPrice = 10.8,
        open = 12.7,
        high = 12.7,
        low = 12.7,
        close = 12.7,
        average = 12.7,
        adOpen = 12.7,
        adHigh = 12.7,
        adLow = 12.7,
        adClose = 12.7,
        adAverage = 12.7,
        nmVolume = 0.0,
        nmValue = 0.0,
        ptVolume = 0.0,
        ptValue = 0.0,
        change = 0.0,
        adChange = 0.0,
        pctChange = 0.0
    ),
    StockPrice(
        code = "POV",
        date = "2022-10-06",
        time = "15:10:01",
        floor = "UPCOM",
        type = "STOCK",
        basicPrice = 10.1,
        ceilingPrice = 11.6,
        floorPrice = 8.6,
        open = 10.2,
        high = 10.6,
        low = 10.1,
        close = 10.1,
        average = 10.28,
        adOpen = 10.2,
        adHigh = 10.6,
        adLow = 10.1,
        adClose = 10.1,
        adAverage = 10.28,
        nmVolume = 4000.0,
        nmValue = 41120000.0,
        ptVolume = 0.0,
        ptValue = 0.0,
        change = 0.0,
        adChange = 0.0,
        pctChange = 0.0
    ),
    StockPrice(
        code = "HFX",
        date = "2022-10-06",
        time = "15:10:01",
        floor = "UPCOM",
        type = "STOCK",
        basicPrice = 8.6,
        ceilingPrice = 9.8,
        floorPrice = 7.4,
        open = 8.6,
        high = 8.6,
        low = 8.6,
        close = 8.6,
        average = 8.6,
        adOpen = 8.6,
        adHigh = 8.6,
        adLow = 8.6,
        adClose = 8.6,
        adAverage = 8.6,
        nmVolume = 0.0,
        nmValue = 0.0,
        ptVolume = 0.0,
        ptValue = 0.0,
        change = 0.0,
        adChange = 0.0,
        pctChange = 0.0
    ),
    StockPrice(
        code = "DC2",
        date = "2022-09-16",
        time = "15:09:03",
        floor = "HNX",
        type = "STOCK",
        basicPrice = 9.4,
        ceilingPrice = 10.3,
        floorPrice = 8.5,
        open = 8.6,
        high = 9.1,
        low = 8.5,
        close = 8.9,
        average = 8.602,
        adOpen = 8.6,
        adHigh = 9.1,
        adLow = 8.5,
        adClose = 8.9,
        adAverage = 8.602,
        nmVolume = 4206.0,
        nmValue = 36181600.0,
        ptVolume = 0.0,
        ptValue = 0.0,
        change = -0.5,
        adChange = -0.5,
        pctChange = -5.3191
    ),
    StockPrice(
        code = "DC2",
        date = "2022-09-15",
        time = "15:09:02",
        floor = "HNX",
        type = "STOCK",
        basicPrice = 9.5,
        ceilingPrice = 10.4,
        floorPrice = 8.6,
        open = 9.5,
        high = 9.5,
        low = 8.9,
        close = 9.4,
        average = 9.13,
        adOpen = 9.5,
        adHigh = 9.5,
        adLow = 8.9,
        adClose = 9.4,
        adAverage = 9.13,
        nmVolume = 2797.0,
        nmValue = 25497800.0,
        ptVolume = 0.0,
        ptValue = 0.0,
        change = -0.1,
        adChange = -0.1,
        pctChange = -1.0526
    ),
)
